### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Phoenix1112** [Damian89/extended-xss-search#7]
what is problem??

python3 extended-xss-search.py

```
[ i ] Mode:			Default mode
[ i ] GET:			active with chunk size of 150
[ i ] POST:			active with chunk size of 500
[ i ] Threads:			5
[ i ] HTTP Timeout:		10
[ i ] Proxy server:		127.0.0.1:8080
[ i ] Cookies used:		_gcl_au=1.1.946326128.1568820734; cto_lwid=eec0a61a-b915-4247-84ce-0e46bdd6d49e; _ga=GA1.3.1531886190.1568820752; _gid=GA1.3.2082234944.1568820752; __insp_wid=1175876999; __insp_slim=1568821823887; __insp_nv=true; __insp_targlpu=aHR0cHM6Ly9wYXJraW5nLmtpd2kuY29tL2ZyLUZSLw%3D%3D; __insp_targlpt=UsOpc2VydmVyIHVuZSBwbGFjZSBkZSBwYXJraW5nIC0gS2l3aQ%3D%3D; country=FR; currency=EUR; language=fr; __insp_pad=5; __insp_sid=2402758595; __insp_uid=2903879610; _fbp=fb.1.1568820770522.281341923; _ga=GA1.2.849149921.1568820770; _gid=GA1.2.1421333592.1568820770; tjex=eJwrsTU0NbOwMDI0MTGzNDfXS7UFACiyBDY%3D; ADRUM=s=1568821607539&r=https%3A%2F%2Fcars.kiwi.com%2F%3F-76104662; cto_idcpy=aeba714c-5e9d-461c-b201-901289837d87; tj_seed=003f140f84b76bd56aa119412484000000; tj_cip_correlation_id=69E47683C0B7E397CADA985C4AFF888C; CONNECTIONID=1568801357810|as-435|11502; tj_conf="tj_pref_currency:TRY|tj_pref_lang:tr|tjcor:tr|"; tj_track=YWZmaWxpYXRlQ29kZTpza3lwaWNrZXJ8;
[ i ] Added headers:		Accept: */*, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
[ i ] Initial url count:	1
[ i ] Cleaned url count:	1
Traceback (most recent call last):
  File "extended-xss-search.py", line 153, in <module>
    main()
  File "extended-xss-search.py", line 40, in main
    base_tests = PrepareBaseRequest(config).tests
  File "/home/CyberTheReapeR/extended-xss-search/inc/preparation/PrepareBaseRequest.py", line 29, in __init__
    self.__create_request_data()
  File "/home/CyberTheReapeR/extended-xss-search/inc/preparation/PrepareBaseRequest.py", line 39, in __create_request_data
    self.__add_test(url, hostname, port, path)
  File "/home/CyberTheReapeR/extended-xss-search/inc/preparation/PrepareBaseRequest.py", line 45, in __add_test
    headers.add_user_defined_headers()
  File "/home/CyberTheReapeR/extended-xss-search/inc/Headers.py", line 31, in add_user_defined_headers
    name, value = header_string.split(":")
ValueError: too many values to unpack (expected 2)```

**Comment by Damian89** [comment]
Hi,
the tool currently is pretty stupid regarding header creation, you added:

Accept: */*, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

and here is: "rv:60.0" the problem. It contains a ":" which is the character to split stuff up. I currently have zero time to fix this, but it should not be hard. I think someone fixed it already in some other tool - extended-ssrf-search - its based on the same code so maybe you just look into the last commits there ;)

Best,

Damian

**Comment by Phoenix1112** [comment]
firstly thank you for your quick reply. I can't understand some things because I don't know English. I set the burp proxy settings from app-settings.conf to "true". I want to use this program simultaneously with the burp suite. I'm trying to start the program while the burp suite program is open, and the result is as follows:

```
[ i ] Mode:			Default mode
[ i ] GET:			active with chunk size of 150
[ i ] POST:			active with chunk size of 500
[ i ] Threads:			5
[ i ] HTTP Timeout:		10
[ i ] Proxy server:		127.0.0.1:8080
[ i ] Added headers:		Accept: */*, User-Agent: XSS Tester
[ i ] Initial url count:	1
[ i ] Cleaned url count:	1
[ i ] Executing 1 base requests...
[ i ] Worker 0 started...
[ i ] Worker 1 started...
[ i ] Worker 2 started...
[ i ] Worker 3 started...
[ i ] Worker 4 started...
[ x ] [Proc: 0] http://://None// [expected string or bytes-like object]
[ i ] Finished with 1 base requests...
[ i ] Preparing finale attack requests...
[ i ] Executing 4 attacks/tests... could take a while!
[ i ] Worker 0 started...
[ i ] Worker 1 started...
[ i ] Worker 2 started...
[ i ] Worker 3 started...
[ i ] Worker 4 started...
[ x ] [Proc: 0] http://://None// [expected string or bytes-like object]
[ x ] [Proc: 1] http://://None// [expected string or bytes-like object]
[ x ] [Proc: 2] http://://None// [expected string or bytes-like object]
[ x ] [Proc: 3] http://://None// [expected string or bytes-like object]
```
I didn't add any url to the config/urls-to-test.txt list when I wanted to work with burp suite. because I thought it would pull all url addresses from the burp suite. am I wrong about that?

Is it wrong to think that the program should see all the requests I view with the burp suite? please help me with this.

**Comment by Damian89** [comment]
"am I wrong about that?"

yes.

You have to provide a list of urls and burp is just used as a proxy - that way you can inspect all those requests later on in burp and/or make use of the passive modules in parallel.

**Comment by Phoenix1112** [comment]
i understand now... thanks.... if you want you can close this issue
